- name: Setup server
  hosts: all
  become: yes

  tasks:
    - name: Install curl
      ansible.builtin.yum:
        name: curl
        state: present

    # https://docs.k3s.io/installation/requirements?os=rhel#operating-systems
    - name: Ensure firewalld is disabled
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
      failed_when: false

    - name: Check if k3s is already installed
      ansible.builtin.stat:
        path: /etc/rancher/k3s/kubelet.conf
      register: kubelet_conf_file

    - name: Install k3s
      ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -
      when: not kubelet_conf_file.stat.exists
