name: Terraform CI/CD

# Configure the pipeline to run on pull requests and pushes to the 'main' branch.
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
	  - develop
  workflow_dispatch:

env:
  TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

permissions:
  contents: read
  pull-requests: write
  id-token: write

defaults:
  run:
    working-directory: iac

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: af-south-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=plan.out

      - name: Save plan as JSON
        run: terraform show -json plan.out > plan.json

      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: |
            iac/plan.out
            iac/plan.json


  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.event_name == 'workflow_dispatch' # only run on if triggered manually by me
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: plan.out

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: af-south-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Terraform Apply
        run: terraform apply -auto-approve plan.out

